name: Build and deploy to pypi

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Build distribution
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/python-tado

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: '.python-version'
      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: python3 -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v5
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
